version: "3.9"

services:
  astro:
    image: astro-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./site:/app/site
      - /app/site/node_modules
    environment:
      - NODE_ENV=development
      - PUBLIC_SANITY_PROJECT_ID=4kjxjblw
      - PUBLIC_SANITY_DATASET=production
      - SANITY_AUTH_TOKEN=${SANITY_AUTH_TOKEN:-}
    networks:
      - zorakle-new_sail
networks:
  zorakle-new_sail:
    external: true

